idf_component_register(  
    SRCS "app_main.c"  
    INCLUDE_DIRS "."  
    REQUIRES   
        esp_wifi   
        esp_system   
        nvs_flash   
        esp_event   
        esp_netif   
        protocol_examples_common   
        freertos   
        lwip   
        esp_log   
        mqtt_client   
        driver  
        qrcodegen  
)  

